// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OSC_Stream.Data;

#nullable disable

namespace OSC_Stream.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705150240_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OSC_Stream.Models.Accounts.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("accountId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasJsonPropertyName("displayName");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasJsonPropertyName("email");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasJsonPropertyName("password");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasJsonPropertyName("profileImage");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .HasColumnType("text[]")
                        .HasJsonPropertyName("roles");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasJsonPropertyName("username");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
