// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OSC_Stream.Data;

#nullable disable

namespace OSC_Stream.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OSC_Stream.Models.Accounts.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("accountId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasJsonPropertyName("displayName");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasJsonPropertyName("email");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasJsonPropertyName("password");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasJsonPropertyName("profileImage");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .HasColumnType("text[]")
                        .HasJsonPropertyName("roles");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasJsonPropertyName("username");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OSC_Stream.Models.Shows.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateReleased")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dateReleased");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<int?>("ShowId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("showId");

                    b.Property<string>("VideoId")
                        .HasColumnType("text")
                        .HasJsonPropertyName("videoId");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("Episode");

                    b.HasAnnotation("Relational:JsonPropertyName", "episodes");
                });

            modelBuilder.Entity("OSC_Stream.Models.Shows.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImage")
                        .HasColumnType("text")
                        .HasJsonPropertyName("bannerImage");

                    b.Property<string>("Creator")
                        .HasColumnType("text")
                        .HasJsonPropertyName("creator");

                    b.Property<DateTime>("DateReleased")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dateReleased");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("OSC_Stream.Models.Shows.Episode", b =>
                {
                    b.HasOne("OSC_Stream.Models.Shows.Show", null)
                        .WithMany("Episodes")
                        .HasForeignKey("ShowId");
                });

            modelBuilder.Entity("OSC_Stream.Models.Shows.Show", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
